spring.profiles.active=local
spring.datasource.url=jdbc:h2:tcp://localhost/~/test
spring.datasource.username=sa
spring.datasource.password=


#logging.level.org.springframework.jdbc=debug
#logging.level.root=debug

# 'openApi.gwon.movieList' ???? ?? ?? ??? DEBUG? ??
logging.level.openApi.gwon.movieList=DEBUG

# ?? ?????? ?? ??? INFO? ??
logging.level.root=INFO

#MyBatis
mybatis.type-aliases-package=gwon.movieList
mybatis.configuration.map-underscore-to-camel-case=true


#jsp
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
# ??? ?? jsp ??
server.servlet.jsp.init-parameters.development=true


logging.level.openApi = DEBUG
logging.level.openApi.gwon.movieList.mapper = DEBUG

#
mybatis.mapper-locations=classpath*:mapper/*.xml


# Mailgun
mailgun.api.key=42b6076d3cf1bf85debb4d53a6b0b83b-7113c52e-37f6aceb

mailgun.domain=sandbox5ac56c03c1534e9892254baf24905bd5.mailgun.org

mailgun.from=Excited User <mailgun@sandbox5ac56c03c1534e9892254baf24905bd5.mailgun.org>








